version: '3.8'

services:
  chrony:
    image: ghcr.io/glassrom/chrony-docker:master
    read_only: true
    container_name: chrony
    user: "999:999"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    ports:
      - "123:123/udp"
    volumes:
      # gvisor DNS fixup
      - type: bind
        source: /etc/resolv-container-chrony.conf
        target: /etc/resolv.conf
        read_only: true
        bind:
          selinux: z
    tmpfs:
      - /var/run/chrony:uid=999,gid=999
      - /run/chrony:uid=999,gid=999
    restart: always
    pull_policy: always
    depends_on:
      - unbound-chrony
    networks:
      - chrony_net
    runtime: runsc-overlay

  unbound-chrony:
    runtime: runsc-overlay
    image: ghcr.io/glassrom/dns-docker:master
    read_only: true
    container_name: unbound-chrony
    user: "970:970"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CAP_NET_BIND_SERVICE
      - CAP_SYS_RESOURCE
      - CAP_NET_RAW
    tmpfs:
      - /tmp
    restart: always
    pull_policy: always
    networks:
      chrony_net:
        ipv4_address: 172.25.0.2

networks:
  chrony_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16
          gateway: 172.25.0.1
