version: '3.8'

services:
  chrony:
    image: f3a7704f605d4c84205e6f604695d92b9de8434966c3af8b5745c05b142ed45a
    read_only: true
    container_name: chrony
    user: "999:999"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    ports:
      - "123:123/udp"
    pull_policy: never
    volumes:
      # gvisor DNS fixup
      - type: bind
        source: /etc/resolv-container-chrony.conf
        target: /etc/resolv.conf
        read_only: true
        bind:
          selinux: z
    tmpfs:
      - /var/run/chrony:uid=999,gid=999
      - /run/chrony:uid=999,gid=999
    restart: always
    depends_on:
      - unbound-chrony
    networks:
      - chrony_net
    runtime: runsc

  unbound-chrony:
    runtime: runsc
    image: 16f89696db27eb4e0c3874e7020f6a5c727350e3e6ac3ac87c94010cc003f688
    read_only: true
    container_name: unbound-chrony
    user: "970:970"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    tmpfs:
      - /tmp
    restart: always
    pull_policy: never
    networks:
      chrony_net:
        ipv4_address: 172.25.0.2

networks:
  chrony_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16
          gateway: 172.25.0.1
